# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "pretty-compact";
  version = "1.0";
  src = ./.;
  meta = {
    description = "Pretty-printing library";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
